### ISSUE TITLE
[Bug] EventEmitter Memory leak

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#102]
So far the fixes that you've found makeshift don't work.
Using `process.setMaxListeners(100000);` we still get the error once on startup. It doesn't seem to reoccur. 

```
2018-04-30T23:09:05.423Z [info] [undefined/P:\xampp\htdocs\waitlist\eve-goons-waitlist\index.js]: Express online and accepting connections
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.logPossibleMemoryLeak (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\eventemitter2\lib\eventemitter2.js:53:15)
    at EventEmitter.growListenerTree (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\eventemitter2\lib\eventemitter2.js:218:35)
    at EventEmitter.on (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\eventemitter2\lib\eventemitter2.js:492:24)
    at EventEmitter.many (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\eventemitter2\lib\eventemitter2.js:269:10)
    at EventEmitter.once (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\eventemitter2\lib\eventemitter2.js:249:10)
    at sub (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express-longpoll\index.js:135:36)
    at _app.get (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express-longpoll\index.js:142:21)
    at Layer.handle [as handle_request] (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\layer.js:95:5)
    at next (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\route.js:137:13)
    at longpoll.create (P:\xampp\htdocs\waitlist\eve-goons-waitlist\index.js:117:3)
    at Layer.handle [as handle_request] (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\layer.js:95:5)
    at next (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\layer.js:95:5)
    at P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\index.js:281:22
    at param (P:\xampp\htdocs\waitlist\eve-goons-waitlist\node_modules\express\lib\router\index.js:354:14)
```

**Comment by Makeshift** [comment]
If you set it to 0 that should be the equivalent of unlimited. If it only warns once I wouldn't mind so much, are you sure it doesn't continue spamming like crazy like it does now?

**Comment by samuelgrant** [comment]
Tried 0 and it didn't have the desired effect so I added lots of 0s and a one.  Now that I think about it I don't think I restarted node so I am going to try that again. As it stands it is only sending one error to log.

**Comment by samuelgrant** [comment]
This should be resolved by pull request #106 . I wont close this ticket until we test the waitlist under load during the next spawn

**Comment by Makeshift** [comment]
Still happening. I may roll my own long-polling package to fix this.
